# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: egaylord <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/12 14:44:51 by egaylord          #+#    #+#              #
#    Updated: 2019/08/13 16:47:56 by egaylord         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
OBJ = main.c function.c
FLAGS = -Wall -Wextra -Werror

all: $(NAME)
	gcc $(FLAGS) $(OBJ) -o $(NAME)

clean:
	rm -rf $(NAME)
